# Generated by Django 4.0.6 on 2022-07-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
