# Generated by Django 4.0.6 on 2022-07-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_address_business_booth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='booth',
            new_name='address',
        ),
    ]
